# golangci-lint configuration (v2)
# Standard configuration for gzh-cli-* projects

version: "2"

run:
  go: "1.24"
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - fmt.Print
        - fmt.Println
        - fmt.Printf

    goconst:
      min-len: 3
      min-occurrences: 3

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance

    gocyclo:
      min-complexity: 15

    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow

    misspell:
      locale: US

    nakedret:
      max-func-lines: 30

    prealloc:
      simple: true
      range-loops: true
      for-loops: true

    revive:
      rules:
        - name: blank-imports
          disabled: false
        - name: context-as-argument
          disabled: false
        - name: error-return
          disabled: false
        - name: error-strings
          disabled: false
        - name: error-naming
          disabled: false
        - name: exported
          disabled: false
        - name: increment-decrement
          disabled: false
        - name: var-naming
          disabled: false
        - name: package-comments
          disabled: true
        - name: indent-error-flow
          disabled: false

    staticcheck:
      checks:
        - all

  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - gosec
          - gocritic
        path: _test\.go

      - linters:
          - errcheck
        text: Error return value of.*Close.*is not checked

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
  new: false
